name: Create Runners
on:
  repository_dispatch:
    types: [create-runners]

jobs:
  create-runners:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run config.sh
        run: .github/workflows/config.sh --url shivapaga/runner-repo --token ${{ secrets.RUNNER_TOKEN }} --name my-runner --labels "label1,label2"
