name: Create Runners
on:
  repository_dispatch:
    types: [create-runners]

jobs:
  create-runners:
    runs-on: ubuntu-latest
    steps:
      - name: Create Runners in runner-repo
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/your-username/app1/actions/runners/registration-token \
          | jq -r .token > token.txt

          export RUNNER_TOKEN=$(cat token.txt)
          
          # Register runners
          ./config.sh --url https://github.com/shivapaga/runner-repo --token $RUNNER_TOKEN --name my-runner --labels label1,label2
